server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  # SPA (Ionic React Router) — qualquer rota cai no index
  location / { try_files $uri $uri/ /index.html; }
  location = /index.html { add_header Cache-Control "no-cache"; }
}
